### ISSUE TITLE
Interrupts are disabled during enclave execution

### ISSUE THREAD

**Issue by dkohlbre** [keystone-enclave/riscv-pk#11]
Since the runtime doesn't currently handle interrupts, we've had to disable them during execution on real hardware (sifive-keystone branch).
This is less of an issue in qemu which isn't generating the same interrupt sources.

See: https://github.com/keystone-enclave/riscv-pk/commit/d14704138e24e1f8116fe31d9062fa70ae644fab

**Comment by dayeol** [comment]
doesn't the newer linux driver fixes the problem?
https://github.com/keystone-enclave/keystone/issues/44

**Comment by dayeol** [comment]
Closing
