### ISSUE TITLE
get_host_satp() returns unsigned long, but internally uses a return value of -1

### ISSUE THREAD

**Issue by david-oswald** [keystone-enclave/riscv-pk#15]
As described in the title: the declaration is unsigned long ```get_host_satp(unsigned int eid)```, but the function returns -1 to indicate an error:

https://github.com/keystone-enclave/riscv-pk/blob/keystone/sm/enclave.c#L82

I don't think that this currently causes any significant problem due to the way ```get_host_satp()``` is used so far, but it might lead to subtle issues in the future. I'd suggest having a more explicit error handling here.

**Comment by dkohlbre** [comment]
Good catch. I'll switch that to the standardized enclave return type.

Surprised I didn't see a warning in the build, I'll need to go check if we have more of these (and why we didn't get a warning)
