### ISSUE TITLE
Security monitor should swap all S-mode CSRs on context switch

### ISSUE THREAD

**Issue by dayeol** [keystone-enclave/riscv-pk#34]
The security monitor needs to swap all relevant S-mode CSRs on context switch between the enclave and the host.
Right now, we only swap important CSRs: satp and stvec

**Comment by dkohlbre** [comment]
This was done in https://github.com/keystone-enclave/riscv-pk/commit/3a2df8acf8581b305dee42e203a729f7c410c8c2
