### ISSUE TITLE
A known bug in cache partitioning

### ISSUE THREAD

**Issue by dayeol** [keystone-enclave/riscv-pk#44]
There was high variation in the execution time of baseline benchmarks.
We suspect that the cache partitioning might had a bug which does not clear the partitioning metadata on enclave exit.
We need to check cause we're not sure if it's been fixed already.

**Comment by dkohlbre** [comment]
This is probably fixed in: https://github.com/keystone-enclave/riscv-pk/pull/49
Once we've run tests we can close this.
