### ISSUE TITLE
Write a part of SM in Rust

### ISSUE THREAD

**Issue by dayeol** [keystone-enclave/riscv-pk#51]
This will let us know how feasible/easy to translate current SM into Rust with current upstream toolchain status.

**Comment by archshift** [comment]
I've managed to get things building and I've rewritten cpu.c and sm.c in Rust to start seeing how integration can work. You can see the rough progress at a8b6db591c2c938ff98b26276a1cfdc49032e7a2, but things still need some cleanups.

**Comment by archshift** [comment]
Once rust-lang/rust#65953 is merged I can remove a lot of the unfortunate build system contortions I needed to use because of hard float issues.
